title: Seonghun's Blog
author: Seonghun Park
email: seonghun120614@gmail.com
description: > # this means to ignore newlines
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
show_excerpts: true
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "" # the base hostname & protocol for your site, e.g. http://example.com
domain: seonghun120614.github.io
url: https://seonghun120614.github.io
baseurl: "/seonghun120614"
twitter_username: jekyllrb
github_username:  seonghun120614

exclude:
  - _posts/template.md
  - new_post.sh
  - assets/scss

# Build settings
remote_theme: samarsault/plainwhite-jekyll
plugins:
  - jekyll-feed

plainwhite:
  name: Seonghun Park
  tagline: Developer.
  date_format: "%b %-d, %Y"
  html_lang: "kor"
  analytics-id: "G-RQTWJRLWGD"
  portfolio_image: "assets/portfolio.png"
  portfolio_image_dark: "assets/portfolio.png"
  disqus_shortname: seonghun
  sitemap: true
  dark_mode: true
  excerpt_separator: "<!--more-->"
  search: true

  social_links:
    github: seonghun120614
    google: seonghun120614
    instagram: stellar__cloud.ig

  navigation:
    - title: About Me
      url: "/seonghun120614/about"

  condensed_mobile:
    - home
    - post
    - page
